name: frontend
description: RoastOrToast - AI Roast & Compliment App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  http: ^1.6.0
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  image_picker: ^1.2.1
  google_fonts: ^6.3.2
  razorpay_flutter: ^1.4.0
  share_plus: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"